/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory;

import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.User;

/**
 *
 * @author bendrhick
 */
public class ItemOption extends javax.swing.JFrame {

    /**
     * Creates new form ItemOption
     */
    private static User sessionUser = null;
    public ItemOption(User user) {
        initComponents();
        this.sessionUser = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddNewItem = new javax.swing.JButton();
        btnEditItem = new javax.swing.JButton();
        btnDeleteItem = new javax.swing.JButton();
        btnReplenishStock = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnDepleteStock = new javax.swing.JButton();
        btnMainMenu = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAddNewItem.setText("Add New Item");
        btnAddNewItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewItemActionPerformed(evt);
            }
        });

        btnEditItem.setText("Edit Item");
        btnEditItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditItemActionPerformed(evt);
            }
        });

        btnDeleteItem.setBackground(new java.awt.Color(255, 51, 0));
        btnDeleteItem.setText("Delete Item");
        btnDeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteItemActionPerformed(evt);
            }
        });

        btnReplenishStock.setText("Replenish Stock");
        btnReplenishStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReplenishStockActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Item Option");

        btnDepleteStock.setBackground(new java.awt.Color(255, 0, 0));
        btnDepleteStock.setText("Deplete Stock");
        btnDepleteStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepleteStockActionPerformed(evt);
            }
        });

        btnMainMenu.setText("Main Menu");
        btnMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainMenuActionPerformed(evt);
            }
        });

        jButton1.setText("Scan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddNewItem, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addComponent(btnDeleteItem, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEditItem, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReplenishStock, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDepleteStock, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(btnMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddNewItem)
                    .addComponent(btnDeleteItem))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditItem)
                    .addComponent(btnDepleteStock))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReplenishStock)
                    .addComponent(jButton1))
                .addGap(32, 32, 32)
                .addComponent(btnMainMenu)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainMenuActionPerformed

        try {
            this.setVisible(false);
            MainMenu menu = new MainMenu(this.sessionUser);
            menu.setTitle("DSL Inventory System | Main Menu");
            menu.pack();
            menu.setLocationRelativeTo(null);
            menu.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ItemOption.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ItemOption.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(ItemOption.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMainMenuActionPerformed

    private void btnAddNewItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewItemActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AddNewItem newItem = new AddNewItem(this.sessionUser);
        newItem.setTitle("DSL Inventory System | Add New Item");
        newItem.pack();
        newItem.setLocationRelativeTo(null);
        newItem.setVisible(true);
    }//GEN-LAST:event_btnAddNewItemActionPerformed

    private void btnEditItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditItemActionPerformed
        try {
            // TODO add your handling code here:
            InventoryOverview io = new InventoryOverview(this.sessionUser, "Edit");
            io.setTitle("DSL Inventory System | List of Items");
            io.pack();
            io.setLocationRelativeTo(null);
            io.setVisible(true);
//        this.setVisible(false);
//        EditItem editItem = new EditItem(this.sessionUser);
//        editItem.setTitle("DSL Inventory System | Edit Item");
//        editItem.pack();
//        editItem.setLocationRelativeTo(null);
//        editItem.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ItemOption.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ItemOption.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEditItemActionPerformed

    private void btnReplenishStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReplenishStockActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            InventoryOverview io = new InventoryOverview(this.sessionUser, "Replenish");
            io.setTitle("DSL Inventory System | List of Items");
            io.pack();
            io.setLocationRelativeTo(null);
            io.setVisible(true);
//        this.setVisible(false);
//        EditItem editItem = new EditItem(this.sessionUser);
//        editItem.setTitle("DSL Inventory System | Edit Item");
//        editItem.pack();
//        editItem.setLocationRelativeTo(null);
//        editItem.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ItemOption.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ItemOption.class.getName()).log(Level.SEVERE, null, ex);
        }
//        // TODO add your handling code here:this.setVisible(false);
//        Replenish replenish = new Replenish(this.sessionUser);
//        replenish.setTitle("DSL Inventory System | Replenish Stock");
//        replenish.pack();
//        replenish.setLocationRelativeTo(null);
//        replenish.setVisible(true);
        
    }//GEN-LAST:event_btnReplenishStockActionPerformed

    private void btnDepleteStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepleteStockActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            InventoryOverview io = new InventoryOverview(this.sessionUser, "Deplete");
            io.setTitle("DSL Inventory System | List of Items");
            io.pack();
            io.setLocationRelativeTo(null);
            io.setVisible(true);
//        this.setVisible(false);
//        EditItem editItem = new EditItem(this.sessionUser);
//        editItem.setTitle("DSL Inventory System | Edit Item");
//        editItem.pack();
//        editItem.setLocationRelativeTo(null);
//        editItem.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ItemOption.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ItemOption.class.getName()).log(Level.SEVERE, null, ex);
        }

//        // TODO add your handling code here:
//        Deplete deplete = new Deplete(this.sessionUser);
//        deplete.setTitle("DSL Inventory System | Deplete Stock");
//        deplete.pack();
//        deplete.setLocationRelativeTo(null);
//        deplete.setVisible(true);
    }//GEN-LAST:event_btnDepleteStockActionPerformed

    private void btnDeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteItemActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            InventoryOverview io = new InventoryOverview(this.sessionUser, "Delete");
            io.setTitle("DSL Inventory System | List of Items");
            io.pack();
            io.setLocationRelativeTo(null);
            io.setVisible(true);
//        this.setVisible(false);
//        EditItem editItem = new EditItem(this.sessionUser);
//        editItem.setTitle("DSL Inventory System | Edit Item");
//        editItem.pack();
//        editItem.setLocationRelativeTo(null);
//        editItem.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ItemOption.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ItemOption.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewItem;
    private javax.swing.JButton btnDeleteItem;
    private javax.swing.JButton btnDepleteStock;
    private javax.swing.JButton btnEditItem;
    private javax.swing.JButton btnMainMenu;
    private javax.swing.JButton btnReplenishStock;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
